### ISSUE TITLE
openssl not available on latest nginx 

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/st2box#7]
This change here updates the nginx Dockerfile to not install `ca-certificates` https://github.com/nginxinc/docker-nginx/commit/ec7ff8c0a3d58aba0e812598c2a7b7869aba985d#diff-2aaa25af4e5df3dd6c91b501b3d9c630L25

This means that openssl is not installed, which means that st2box builds fail.

Options:
- Use an earlier version of the nginx container - e.g. 1.10
- Update our Dockerfile to install openssl
- Generate certificates outside the container and copy them in

Thoughts @enykeev ?

**Comment by enykeev** [comment]
Another option is to move from st2box to our new docker container. The ones you provided are also all valid. Feel free to pick the easier one.

**Comment by LindsayHill** [comment]
Yeah. Moving to new containers will be the better approach long-term. I might just pin our nginx container version here, as the least intrusive change, and then we move to st2-docker for long-term

**Comment by LindsayHill** [comment]
Fixed with #8
